### PR TITLE
Tweaks to Admin Lookup based on Phyllis' suggestions

### PR DESCRIPTION
**Pull request by jhanstra**
image

- Margin around the alert
- Bold search and better wording to be more action-oriented
- Placeholder text in search box
- Clean up in the code to not use inline styles

### CODE REVIEW

**Comment by apetro** [comment]
:+1:

**Comment by keirserrie** [comment]
Great--can you put the warning message (for use only in case of emergency) underneath the search/clear buttons?

**Comment by jhanstra** [comment]
@keirserrie great idea, done

**Comment by keirserrie** [comment]
:+1:

**Comment by timlevett** [comment]
:+1:

**Pull request merged**
