### PR TITLE
MUMPFL-115 Show student birthdate

### PR DESCRIPTION
**Pull request by vertein**
Before:

image

After:
image

### CODE REVIEW

**Comment by apetro** [comment]
:+1:

**Comment by timlevett** [comment]
:+1: We may want to use the same format as is on licenses (as that is what they are used to looking at). `#thelittlethings`

**Comment by vertein** [comment]
/me attempts to find wallet to check on what the date format is

**Comment by vertein** [comment]
/me sees that it's MM/DD/YYYY  and through the magic of angular date filters will update before merging.  Good suggestion

**Comment by vertein** [comment]
image

**Pull request merged**
