### PR TITLE
MUMPFL-137 Masks Sensitive Data for Logging

### PR DESCRIPTION
**Pull request by vertein**
Creates a string suitable for logging.  Masks sensitive information per the request of UW Security.

Also logs less on info, and logs the data on error.

Before on emergency contact:
`
[{"edit":true,"preferredName":"Timothy A Vertein","relationship":"Spouse","comments":"","phoneNumbers":[{"type":"mobile","value":"6081234567"}],"emails":[{"type":"primary","value":"jim@googlen.com"}],"addresses":[]}, {"edit":false,"preferredName":"Timothy A Vertein","relationship":"Parent","comments":"","phoneNumbers":[{"type":"mobile","value":"6081234567"},{"type":"mobile","value":"6081234567"},{"type":"mobile","value":"asdfasdf"}],"emails":[{"type":"primary","value":"jim@googlen.com"}],"addresses":[]}, {"edit":false,"preferredName":"Timothy A Vertein","relationship":"Parent","comments":"","phoneNumbers":[{"type":"mobile","value":"6081234567"}],"emails":[{"type":"primary","value":"jim@googlen.com"}],"addresses":[]}]
`
After on emergency contact:
`
[{"edit":true,"preferredName":"XXXXXXXXXXXXXXXXX","relationship":"XXXXXX","comments":"","phoneNumbers":[{"type":"mobile","value":"XXXXXXXXXX"}],"emails":[{"type":"primary","value":"XXXXXXXXXXXXXXX"}],"addresses":[]}, {"edit":false,"preferredName":"XXXXXXXXXXXXX","relationship":"XXXXXX","comments":"","phoneNumbers":[{"type":"mobile","value":"XXXXXXXXXX"},{"type":"mobile","value":"XXXXXXXXX"},{"type":"mobile","value":"XXXXXXXX"}],"emails":[{"type":"primary","value":"XXXXXXXXXXXXXXX"}],"addresses":[]}, {"edit":false,"preferredName":"XXXXXXX X XXXXXXX","relationship":"XXXXXX","comments":"","phoneNumbers":[{"type":"mobile","value":"XXXXXXXXXX"}],"emails":[{"type":"primary","value":"XXXXXXXXXXXXXXX"}],"addresses":[]}]
`

Before local contact:
`
{"lastModified":"2015-11-19T16:11:30.562-06:00","edit":false,"id":"vertein","phoneNumbers":[],"emails":[],"addresses":[{"type":"","addressLines":["12345 Fake St"],"city":"asasdfasMadison","country":"USA","state":"WI","postalCode":"35704asdfs","comment":"","edit":true}]}
`
After local contact:
`
{"lastModified":"2015-11-19T16:11:30.562-06:00","edit":false,"id":"vertein","phoneNumbers":[],"emails":[],"addresses":[{"type":"","addressLines":[XXXXX XXXX XX"],"city":"XXXXXXXXXXXXXXX","country":"XXX","state":"XX","postalCode":"XXXXXXXXXX","comment":"","edit":true,}]}
`
Before phone number:
`
[{"type":"mobile","value":"6081234567"}]
`
After phone number:
`
[{"type":"mobile","value":"XXXXXXXXXX"}]
`

### CODE REVIEW

**Comment by timlevett** [comment]
:+1:

**Comment by nblair** [comment]
That's a lot of X's. Good idea altogether, might want to indicate simply "<set>" or null instead.

**Comment by timlevett** [comment]
@nblair - we did the x's the same length to identify a possible change in middleware restrictions to data.

**Comment by apetro** [comment]
(I adjusted the PR description just now to pretty-format the JSON examples.)

**Pull request merged**
