### PR TITLE
Polish on Polish

### PR DESCRIPTION
**Pull request by jhanstra**
Didn't get a chance to change what needed to be changed in the last pull request because @timlevett had to merge it in for the refactor. So this PR addresses those changes.

image

### CODE REVIEW

**Comment by keirserrie** [comment]
Thanks for the changes. Was trying out the validation, would be best if you don't get the red unless you've done something wrong. Right now as soon as you focus on the field you get:

screenshot 2015-05-21 16 01 11

And field with error doesn't have the red anymore:

screenshot 2015-05-21 16 11 01

**Comment by jhanstra** [comment]
That's actually what the UW UI Toolkit uses as its default for input focus. I would be in favor of changing that default to blue or something though. Form validation is hard when your school color is red!

**Comment by keirserrie** [comment]
Wow, that's pretty bad. Okay, let's tackle this at a later date. :+1:

**Comment by vertein** [comment]
Let's work on getting the toolkit updated.  I like that we used whatever default styling it had.

**Comment by timlevett** [comment]
:+1:

**Pull request closed without merging**
